services:
  - type: web
    name: virtual-closet
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 300
    envVars:
      - key: REPLICATE_API_TOKEN
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: INVITE_CODE
        sync: false
